[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "22"
  PYENV_VERSION = "3.10.13"
  # Skip submodule processing since this repo does not use submodules
  GIT_SUBMODULE_STRATEGY = "none"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://images.pexels.com https://*.supabase.co https://*.netlify.app; connect-src 'self' https://*.supabase.co https://api.openai.com https://api.elevenlabs.io https://api.spoonacular.com https://*.netlify.app wss://*.supabase.co; font-src 'self'; object-src 'none'; frame-src 'self';"

# Custom domain configuration
[[redirects]]
  from = "https://biowell.ai/*"
  to = "/:splat"
  status = 200
  force = true

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200